Repository ynput/ayon-blender, pull requests merged in 2024-09, with the labels that each got.

#26 Fix set frame range and set resolution
  client/ayon_blender/api/ops.py
  client/ayon_blender/api/pipeline.py
Labels: bug

#28 enhancement/AY-6116-blender_allow_handles_frame_range
  client/ayon_blender/api/pipeline.py
  server/settings/main.py
Labels: enhancement

#1 Blender: Expose frame range and unit conversion attributes on publish instances
  client/ayon_blender/api/lib.py
  client/ayon_blender/plugins/create/create_animation.py
  client/ayon_blender/plugins/create/create_camera.py
  client/ayon_blender/plugins/create/create_pointcache.py
  client/ayon_blender/plugins/create/create_render.py
  client/ayon_blender/plugins/create/create_review.py
  client/ayon_blender/plugins/publish/extract_abc.py
  client/ayon_blender/plugins/publish/extract_abc_animation.py
  client/ayon_blender/plugins/publish/extract_camera_abc.py
  client/ayon_blender/plugins/publish/extract_camera_fbx.py
  client/ayon_blender/plugins/publish/extract_fbx.py
Labels: type: enhancement

#42 Fix optional support for Extract USD Model
  client/ayon_blender/plugins/publish/extract_usd.py
Labels: type: bug, community

#49 Fix: Allow single frame review playblast
  client/ayon_blender/plugins/publish/extract_playblast.py
Labels: type: bug

#38 Add load to compositor loader
  client/ayon_blender/api/pipeline.py
  client/ayon_blender/plugins/load/load_image_compositor.py
Labels: type: enhancement, community

#44 Fix frame range attributes for instances + validations
  client/ayon_blender/api/colorspace.py
  client/ayon_blender/api/lib.py
  client/ayon_blender/plugins/create/create_animation.py
  client/ayon_blender/plugins/create/create_camera.py
  client/ayon_blender/plugins/create/create_pointcache.py
  client/ayon_blender/plugins/create/create_render.py
  client/ayon_blender/plugins/create/create_review.py
  client/ayon_blender/plugins/publish/collect_instance_frame_range.py
  client/ayon_blender/plugins/publish/collect_render.py
  client/ayon_blender/plugins/publish/collect_review.py
  client/ayon_blender/plugins/publish/extract_abc.py
  client/ayon_blender/plugins/publish/extract_abc_animation.py
  client/ayon_blender/plugins/publish/extract_camera_abc.py
  client/ayon_blender/plugins/publish/validate_frame_range.py
Labels: type: bug, type: enhancement

#43 Add switch asset support for all loaders inheriting from `BlenderLoader`
  client/ayon_blender/api/plugin.py
  client/ayon_blender/plugins/load/load_image_compositor.py
Labels: type: enhancement, community
