Repository ynput/ayon-blender, pull requests merged in 2024-07, with the labels that each got.

#7 Allow existing QtWidgets.QApplication instance to exist
  client/ayon_blender/api/ops.py
Labels: bug, enhancement

#9 Fix QApplication access on platforms other than Windows
  client/ayon_blender/api/ops.py
Labels: bug

#12 Do not error on unsaved workfile
  client/ayon_blender/plugins/publish/collect_workfile.py
Labels: enhancement

#14 Validator to check on external data path being absolute
  client/ayon_blender/plugins/publish/validate_absolute_external_data_paths.py
  server/settings/publish_plugins.py
Labels: enhancement
