Repository ynput/ayon-blender, pull requests merged in 2024-10, with the labels that each got.

#53 Define app host name
  package.py
Labels: type: maintenance

#56 Settings: Added descriptions for better clarity.
  server/settings/imageio.py
  server/settings/main.py
  server/settings/publish_plugins.py
  server/settings/render_settings.py
Labels: type: enhancement

#62 Fix managing of loaded compositor image nodes
  client/ayon_blender/api/pipeline.py
Labels: type: bug
