Repository ynput/ayon-blender, pull requests merged in 2024-11, with the labels that each got.

#66 Add Load image to Shader Editor for Select mesh
  client/ayon_blender/api/pipeline.py
  client/ayon_blender/plugins/load/load_image_shader.py
Labels: type: enhancement, community

#70 Render path: Do not enforce backslashes to support UNC path.
  client/ayon_blender/api/render_lib.py
Labels: type: bug, community

#73 Load Image to comp or shader: fix applying colorspace
  client/ayon_blender/plugins/load/load_image_compositor.py
  client/ayon_blender/plugins/load/load_image_shader.py
Labels: type: bug, community

#76 Chore: Don't check for 'remove' value
  client/ayon_blender/plugins/publish/collect_review.py
Labels: type: enhancement
