Repository ynput/ayon-blender, pull requests merged in 2025-03, with the labels that each got.

#103 Use `BLENDER_SYSTEM_SCRIPTS` instead of `BLENDER_USER_SCRIPTS`
  client/ayon_blender/addon.py
  client/ayon_blender/api/lib.py
Labels: type: enhancement, community

#80 Return to global view before closing a window
  client/ayon_blender/api/capture.py
Labels: type: bug, community

#107 Raise descriptive error when Blender launched without -python-use-system-env argument
  client/ayon_blender/blender_addon/startup/init.py
Labels: type: enhancement, community

#108 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
