Repository ynput/ayon-blender, pull requests merged in 2025-02, with the labels that each got.

#94 Load Material: Add option box to choose material slot to load to
  client/ayon_blender/plugins/load/load_image_shader.py
Labels: type: enhancement

#95 Create Workfile: Use cached entity queries from CreateContext
  client/ayon_blender/plugins/create/create_workfile.py
Labels: type: enhancement

#98 Repair action for fixing render output directory should be correct when enabling multilayer exr
  client/ayon_blender/api/render_lib.py
  client/ayon_blender/plugins/publish/collect_render.py
  client/ayon_blender/plugins/publish/validate_deadline_publish.py
Labels: type: bug

#102 Fix operator for Blender 4.4+
  client/ayon_blender/api/ops.py
Labels: type: enhancement, community
