Repository ynput/ayon-blender, pull requests merged in 2025-07, with the labels that each got.

#138 Create Blend Scene: Remove `maintain_selection` attribute
  client/ayon_blender/plugins/create/create_blendScene.py
Labels: type: enhancement, community

#136 Append Blend: avoid objects renamed on name clash
  client/ayon_blender/plugins/load/load_blend.py
  client/ayon_blender/plugins/load/load_blendscene.py
Labels: type: bug, community

#115 Replace avalon and openpype related reference with ayon related reference
  client/ayon_blender/api/constants.py
  client/ayon_blender/api/lib.py
  client/ayon_blender/api/ops.py
  client/ayon_blender/api/pipeline.py
  client/ayon_blender/api/plugin.py
  client/ayon_blender/plugins/create/convert_legacy.py
  client/ayon_blender/plugins/create/create_action.py
  client/ayon_blender/plugins/create/create_animation.py
  client/ayon_blender/plugins/create/create_blendScene.py
  client/ayon_blender/plugins/create/create_camera.py
  client/ayon_blender/plugins/create/create_layout.py
  client/ayon_blender/plugins/create/create_model.py
  client/ayon_blender/plugins/create/create_pointcache.py
  client/ayon_blender/plugins/create/create_render.py
  client/ayon_blender/plugins/create/create_review.py
  client/ayon_blender/plugins/create/create_rig.py
  client/ayon_blender/plugins/create/create_usd.py
  client/ayon_blender/plugins/create/create_workfile.py
  client/ayon_blender/plugins/load/load_action.py
  client/ayon_blender/plugins/load/load_animation.py
  client/ayon_blender/plugins/load/load_audio.py
  client/ayon_blender/plugins/load/load_blend.py
  client/ayon_blender/plugins/load/load_blendscene.py
  client/ayon_blender/plugins/load/load_cache.py
  client/ayon_blender/plugins/load/load_camera_abc.py
  client/ayon_blender/plugins/load/load_camera_fbx.py
  client/ayon_blender/plugins/load/load_fbx.py
  client/ayon_blender/plugins/load/load_image_compositor.py
  client/ayon_blender/plugins/load/load_image_shader.py
  client/ayon_blender/plugins/load/load_layout_json.py
  client/ayon_blender/plugins/load/load_look.py
  client/ayon_blender/plugins/publish/collect_instance.py
  client/ayon_blender/plugins/publish/extract_fbx_animation.py
  client/ayon_blender/plugins/publish/extract_layout.py
  client/ayon_blender/plugins/publish/validate_file_saved.py
Labels: type: enhancement, type: maintenance, bump minor

#139 Implementation of Validate No Animation
  client/ayon_blender/plugins/publish/validate_no_animation.py
  server/settings/publish_plugins.py
Labels: type: enhancement

#105 Add Link Scene Loader
  client/ayon_blender/api/pipeline.py
  client/ayon_blender/api/plugin_load.py
  client/ayon_blender/plugins/load/load_blend_link.py
Labels: type: feature

#124 Supports stripping namespace for shader nodes for texture image
  client/ayon_blender/api/lib.py
Labels: type: bug

#134 Include object child hierarchy when publishing Collection instances
  client/ayon_blender/api/plugin.py
  client/ayon_blender/plugins/create/create_animation.py
  client/ayon_blender/plugins/create/create_blendScene.py
  client/ayon_blender/plugins/create/create_pointcache.py
  client/ayon_blender/plugins/create/create_review.py
  client/ayon_blender/plugins/create/create_usd.py
  client/ayon_blender/plugins/publish/collect_instance.py
  client/ayon_blender/plugins/publish/extract_blend.py
Labels: type: enhancement, community

#145 Minor fixes on Blender exporters.
  client/ayon_blender/plugins/publish/extract_fbx.py
  client/ayon_blender/plugins/publish/extract_usd.py
Labels: type: bug, sponsored

#148 Add description to Creators
  client/ayon_blender/plugins/create/create_action.py
  client/ayon_blender/plugins/create/create_animation.py
  client/ayon_blender/plugins/create/create_blendScene.py
  client/ayon_blender/plugins/create/create_camera.py
  client/ayon_blender/plugins/create/create_layout.py
  client/ayon_blender/plugins/create/create_model.py
  client/ayon_blender/plugins/create/create_pointcache.py
  client/ayon_blender/plugins/create/create_render.py
  client/ayon_blender/plugins/create/create_review.py
  client/ayon_blender/plugins/create/create_rig.py
  client/ayon_blender/plugins/create/create_usd.py
Labels: type: enhancement, community

#151 Use removing instances inherited from blenderCreator
  client/ayon_blender/api/plugin.py
  client/ayon_blender/plugins/create/create_blendScene.py
Labels: type: bug
